# Sales Data Calculator

This notebook analyzes a manually created collection of sales values and calculates total sales, average sales, highest sale, and lowest sale.

**Tools:** Python, Jupyter Notebook

In [1]:
# Create a list of sales values
sales = [12000, 15000, 11000, 18000, 22000, 17000, 14000, 25000, 19000, 16000]
sales

[12000, 15000, 11000, 18000, 22000, 17000, 14000, 25000, 19000, 16000]

In [2]:
# Calculate sales statistics
total_sales = sum(sales)
average_sales = total_sales / len(sales)
highest_sale = max(sales)
lowest_sale = min(sales)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Highest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)

Total Sales: 169000
Average Sales: 16900.0
Highest Sale: 25000
Lowest Sale: 11000


In [3]:
# Display the results in a clear format
print(f"Total Sales   : ₹{total_sales:,.2f}")
print(f"Average Sales : ₹{average_sales:,.2f}")
print(f"Highest Sale  : ₹{highest_sale:,.2f}")
print(f"Lowest Sale   : ₹{lowest_sale:,.2f}")

Total Sales   : ₹169,000.00
Average Sales : ₹16,900.00
Highest Sale  : ₹25,000.00
Lowest Sale   : ₹11,000.00


## Result Explanation

- **Total sales:** ₹169,000.00 — the combined value of all 10 sales.
- **Average sales:** ₹16,900.00 — the mean value of a sale.
- **Highest sale:** ₹25,000.00 — the largest value in the list.
- **Lowest sale:** ₹11,000.00 — the smallest value in the list.

Python's built-in `sum()`, `max()`, and `min()` functions make these calculations simple and readable.

## Interview Questions

**1. How can Python help analyze sales data?**  
Python can quickly calculate totals, averages, minimums, maximums, trends, and other statistics. Libraries such as pandas and matplotlib can also be used for larger datasets and visualizations.

**2. What does average sales represent?**  
Average sales represent the typical sale value, calculated by dividing total sales by the number of sales.

**3. How would you find the highest sale?**  
Use Python's `max(sales)` function.